


 :- match(X, Y1), match(X, Y2), Y1 != Y2.
 :- match(X1, Y), match(X2, Y), X1 != X2.
 :- edge(X, Y), not match(X, _), not match(_, Y).
#pos({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, a),match(2, b),match(3, d),match(4, c)  },{ match(3, b),match(4, d),match(2, d),match(3, c),match(1, c),match(2, a),match(1, b),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#pos({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, a),match(2, d),match(3, c)  },{ match(3, b),match(4, d),match(2, b),match(3, d),match(4, c),match(1, c),match(2, a),match(1, b),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#pos({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, a),match(3, b),match(2, d)  },{ match(4, d),match(3, c),match(2, b),match(3, d),match(4, c),match(1, c),match(2, a),match(1, b),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#pos({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, a),match(3, b),match(4, d)  },{ match(2, d),match(3, c),match(2, b),match(3, d),match(4, c),match(1, c),match(2, a),match(1, b),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#pos({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, a),match(4, d),match(3, c),match(2, b)  },{ match(3, b),match(2, d),match(3, d),match(4, c),match(1, c),match(2, a),match(1, b),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#pos({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(2, b),match(3, d),match(1, c),match(4, a)  },{ match(1, a),match(3, b),match(4, d),match(2, d),match(3, c),match(4, c),match(2, a),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#pos({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(2, d),match(3, c),match(1, b),match(4, a)  },{ match(1, a),match(3, b),match(4, d),match(2, b),match(3, d),match(4, c),match(1, c),match(2, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#pos({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(2, d),match(4, c),match(1, b)  },{ match(1, a),match(3, b),match(4, d),match(3, c),match(2, b),match(3, d),match(1, c),match(2, a),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#pos({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(3, b),match(2, d),match(1, c),match(4, a)  },{ match(1, a),match(4, d),match(3, c),match(2, b),match(3, d),match(4, c),match(2, a),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#pos({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(3, b),match(4, c),match(2, a)  },{ match(1, a),match(4, d),match(2, d),match(3, c),match(2, b),match(3, d),match(1, c),match(1, b),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#pos({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(3, b),match(4, d),match(1, c),match(2, a)  },{ match(1, a),match(2, d),match(3, c),match(2, b),match(3, d),match(4, c),match(1, b),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#pos({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(3, c),match(2, b),match(4, a)  },{ match(1, a),match(3, b),match(4, d),match(2, d),match(3, d),match(4, c),match(1, c),match(2, a),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#pos({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(3, d),match(1, c),match(2, a)  },{ match(1, a),match(3, b),match(4, d),match(2, d),match(3, c),match(2, b),match(4, c),match(1, b),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#pos({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(3, d),match(2, a),match(1, b),match(4, a)  },{ match(1, a),match(3, b),match(4, d),match(2, d),match(3, c),match(2, b),match(4, c),match(1, c)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#pos({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(3, d),match(4, c),match(2, a),match(1, b)  },{ match(1, a),match(3, b),match(4, d),match(2, d),match(3, c),match(2, b),match(1, c),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#pos({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(4, d),match(2, b),match(1, c)  },{ match(1, a),match(3, b),match(2, d),match(3, c),match(3, d),match(4, c),match(2, a),match(1, b),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#pos({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(4, d),match(3, c),match(2, a),match(1, b)  },{ match(1, a),match(3, b),match(2, d),match(2, b),match(3, d),match(4, c),match(1, c),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, a),match(1, b)  },{ match(3, b),match(2, d),match(2, b),match(1, c),match(2, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, a),match(1, b)  },{ match(3, b),match(3, c),match(4, c),match(1, c),match(2, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, a),match(1, b)  },{ match(4, d),match(2, d),match(2, b),match(1, c),match(2, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, a),match(1, c)  },{ match(3, b),match(2, d),match(2, b),match(2, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, a),match(1, c)  },{ match(4, d),match(2, d),match(2, b),match(2, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, a),match(2, a)  },{ match(3, b),match(2, d),match(2, b),match(1, c),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, a),match(2, a)  },{ match(3, b),match(2, d),match(3, c),match(3, d),match(1, c)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, a),match(2, a)  },{ match(3, b),match(3, c),match(2, b),match(1, c),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, a),match(2, a)  },{ match(3, b),match(3, c),match(3, d),match(1, c),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, a),match(2, a)  },{ match(3, b),match(3, c),match(3, d),match(4, c),match(1, c)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, a),match(2, a)  },{ match(3, b),match(3, c),match(4, c),match(1, c),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, a),match(2, a)  },{ match(3, b),match(3, c),match(4, c),match(1, c),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, a),match(2, a)  },{ match(4, d),match(2, d),match(4, c),match(1, c),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, a),match(2, d),match(4, c)  },{ match(3, b),match(4, d),match(3, c),match(2, b),match(3, d),match(1, c),match(2, a),match(1, b),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, a),match(3, b),match(4, c)  },{ match(4, d),match(2, d),match(3, c),match(2, b),match(3, d),match(1, c),match(2, a),match(1, b),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, a),match(4, a)  },{ match(3, b),match(2, d),match(2, b),match(1, c),match(2, a),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, a),match(4, a)  },{ match(3, b),match(3, c),match(2, b),match(1, c),match(2, a),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, a),match(4, a)  },{ match(3, b),match(3, c),match(3, d),match(1, c),match(2, a),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, a),match(4, a)  },{ match(3, b),match(3, c),match(4, c),match(1, c),match(2, a),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, a),match(4, a)  },{ match(4, d),match(2, d),match(2, b),match(1, c),match(2, a),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, c),match(1, b)  },{ match(1, a),match(3, b),match(2, d),match(3, c),match(2, b),match(3, d),match(4, c),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, c),match(1, b)  },{ match(1, a),match(3, b),match(4, d),match(2, d),match(3, c),match(2, b),match(3, d),match(4, c)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, c),match(1, b)  },{ match(1, a),match(3, b),match(4, d),match(2, d),match(3, c),match(2, b),match(4, c),match(2, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, c),match(1, b)  },{ match(1, a),match(3, b),match(4, d),match(3, c),match(2, b),match(3, d),match(4, c),match(2, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(1, c),match(2, a),match(4, a)  },{ match(1, a),match(3, b),match(4, d),match(2, d),match(3, c),match(2, b),match(3, d),match(4, c),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(2, b),match(1, b)  },{ match(1, a),match(3, b),match(4, d),match(2, d),match(3, c),match(1, c),match(2, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(2, b),match(1, b)  },{ match(1, a),match(3, b),match(4, d),match(2, d),match(3, c),match(2, a),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(2, b),match(1, b)  },{ match(1, a),match(3, b),match(4, d),match(2, d),match(3, c),match(3, d),match(2, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(2, b),match(2, a)  },{ match(1, a),match(3, b),match(4, d),match(2, d),match(3, c),match(3, d)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(2, d),match(2, a)  },{ match(1, a),match(3, b),match(4, d),match(2, b),match(3, d),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(2, d),match(2, b)  },{ match(1, a),match(3, b),match(4, d),match(1, c),match(1, b),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(2, d),match(2, b)  },{ match(1, a),match(3, b),match(4, d),match(2, a),match(1, b),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(2, d),match(2, b)  },{ match(1, a),match(3, b),match(4, d),match(3, c),match(1, c),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(2, d),match(2, b)  },{ match(1, a),match(3, b),match(4, d),match(3, c),match(3, d),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(2, d),match(2, b)  },{ match(1, a),match(3, b),match(4, d),match(3, c),match(3, d),match(4, c)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(2, d),match(2, b)  },{ match(1, a),match(3, b),match(4, d),match(3, d),match(1, b),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(2, d),match(2, b)  },{ match(1, a),match(3, b),match(4, d),match(3, d),match(4, c),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(2, d),match(2, b)  },{ match(1, a),match(3, b),match(4, d),match(4, c),match(1, c),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(2, d),match(2, b)  },{ match(1, a),match(3, b),match(4, d),match(4, c),match(2, a),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(2, d),match(3, d)  },{ match(1, a),match(3, b),match(4, d),match(2, b),match(1, c),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(2, d),match(3, d)  },{ match(1, a),match(3, b),match(4, d),match(2, b),match(2, a),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(3, b),match(1, b)  },{ match(1, a),match(2, d),match(3, c),match(2, b),match(3, d),match(2, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(3, b),match(1, b)  },{ match(1, a),match(3, c),match(2, b),match(3, d),match(4, c),match(1, c)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(3, b),match(2, a),match(4, a)  },{ match(1, a),match(4, d),match(2, d),match(3, c),match(2, b),match(3, d),match(4, c),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(3, b),match(2, b)  },{ match(1, a),match(2, d),match(3, c),match(1, c),match(2, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(3, b),match(2, b)  },{ match(1, a),match(3, c),match(1, c),match(2, a),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(3, b),match(2, b)  },{ match(1, a),match(3, c),match(3, d),match(4, c),match(1, c)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(3, b),match(2, b)  },{ match(1, a),match(3, c),match(4, c),match(1, c),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(3, b),match(2, b)  },{ match(1, a),match(3, c),match(4, c),match(1, c),match(2, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(3, b),match(2, b)  },{ match(1, a),match(3, c),match(4, c),match(1, c),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(3, b),match(2, d),match(4, c)  },{ match(1, a),match(4, d),match(3, c),match(2, b),match(3, d),match(1, c),match(2, a),match(1, b),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(3, b),match(3, c)  },{ match(1, a),match(2, d),match(2, b),match(2, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(3, b),match(3, d)  },{ match(1, a),match(2, d),match(3, c),match(2, b),match(2, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(3, c),match(1, c)  },{ match(1, a),match(3, b),match(4, d),match(2, d),match(2, b),match(3, d),match(4, c)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(3, c),match(1, c)  },{ match(1, a),match(3, b),match(4, d),match(2, d),match(3, d),match(4, c),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(3, c),match(2, a),match(4, a)  },{ match(1, a),match(3, b),match(4, d),match(2, d),match(2, b),match(3, d),match(4, c),match(1, c)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(3, c),match(3, d)  },{ match(1, a),match(3, b),match(4, d),match(2, d),match(2, a),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(3, c),match(3, d)  },{ match(1, a),match(3, b),match(4, d),match(2, d),match(2, b),match(2, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(3, c),match(4, c)  },{ match(1, a),match(3, b),match(4, d),match(2, d),match(2, b),match(3, d)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(3, c),match(4, c)  },{ match(1, a),match(3, b),match(4, d),match(2, d),match(3, d),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(4, c),match(1, c)  },{ match(1, a),match(3, b),match(4, d),match(2, d),match(3, c),match(2, b),match(2, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(4, c),match(1, c)  },{ match(1, a),match(3, b),match(4, d),match(2, d),match(3, c),match(2, b),match(3, d)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(4, c),match(4, a)  },{ match(1, a),match(3, b),match(4, d),match(2, d),match(3, c),match(1, c),match(2, a),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(4, c),match(4, a)  },{ match(1, a),match(3, b),match(4, d),match(2, d),match(3, c),match(2, b),match(1, c),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(4, c),match(4, a)  },{ match(1, a),match(3, b),match(4, d),match(2, d),match(3, c),match(2, b),match(1, c),match(2, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(4, c),match(4, a)  },{ match(1, a),match(3, b),match(4, d),match(2, d),match(3, c),match(2, b),match(3, d),match(1, c)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(4, c),match(4, a)  },{ match(1, a),match(4, d),match(3, c),match(2, b),match(3, d),match(1, c),match(2, a),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(4, d),match(2, d)  },{ match(1, a),match(3, b),match(1, c),match(1, b),match(4, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(4, d),match(2, d)  },{ match(1, a),match(3, b),match(2, b),match(1, c),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(4, d),match(2, d)  },{ match(1, a),match(3, b),match(2, b),match(2, a),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(4, d),match(2, d)  },{ match(1, a),match(3, b),match(2, b),match(3, d),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(4, d),match(2, d)  },{ match(1, a),match(3, b),match(3, c),match(1, c),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(4, d),match(3, d)  },{ match(1, a),match(3, b),match(2, d),match(2, b),match(2, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(4, d),match(4, a)  },{ match(1, a),match(3, b),match(2, d),match(2, b),match(3, d),match(4, c),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(4, d),match(4, a)  },{ match(1, a),match(3, b),match(2, d),match(2, b),match(3, d),match(4, c),match(2, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(4, d),match(4, a)  },{ match(1, a),match(3, b),match(2, d),match(3, c),match(2, b),match(3, d),match(4, c)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(4, d),match(4, a)  },{ match(1, a),match(3, b),match(2, d),match(3, c),match(3, d),match(4, c),match(1, c)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(4, d),match(4, c)  },{ match(1, a),match(3, b),match(2, d),match(2, b),match(3, d),match(1, b)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(4, d),match(4, c)  },{ match(1, a),match(3, b),match(2, d),match(2, b),match(3, d),match(2, a)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(4, d),match(4, c)  },{ match(1, a),match(3, b),match(2, d),match(3, c),match(2, b),match(3, d)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).
#neg({edge(1, a),edge(1, b),edge(1, c),edge(2, a),edge(2, b),edge(2, d),edge(3, b),edge(3, c),edge(3, d),edge(4, a),edge(4, c),edge(4, d),match(4, d),match(4, c)  },{ match(1, a),match(3, b),match(2, d),match(3, c),match(3, d),match(1, c)  },{ edge(1, a). edge(1, b). edge(1, c). edge(2, a). edge(2, b). edge(2, d). edge(3, b). edge(3, c). edge(3, d). edge(4, a). edge(4, c). edge(4, d).  }).#modeha(1, match(var(node1),var(node2))).
#modeb( match(var(node1),var(node2))).
#modeb( var(node1) != var(node1), (positive)).
#modeb( var(node2) != var(node2), (positive)).
#modeb( edge(var(node1),var(node2)), (positive)).
#maxhl(1).

